In [53]:
import numpy as np
import pandas as pd
import math

In [54]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()

In [55]:
print(f"IRIS features: \n{iris.feature_names}\n")
print(f"IRIS target: \n{iris.target_names}")

IRIS features: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

IRIS target: 
['setosa' 'versicolor' 'virginica']


In [56]:
X = iris.data
y = iris.target

In [57]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [58]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [60]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [61]:
# Prediction values
y_pred = knn.predict(X_test)
y_pred

array([2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 1, 2, 1, 1, 0, 2, 0, 0, 2,
       2, 0, 1, 2, 1, 1, 0, 2])

In [62]:
# Actual values
y_test

array([2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 2,
       2, 0, 1, 2, 1, 1, 0, 2])

In [63]:
from sklearn.metrics import accuracy_score

print(f"KNN model accuracy: {accuracy_score(y_test, y_pred) * 100}%")

KNN model accuracy: 96.66666666666667%


In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 11]])