In [14]:
import numpy as np
import pandas as pd

In [15]:
social_network_ads_file = "/content/drive/MyDrive/AIML/NAIVE BAYES/social_network_ads.csv"
df = pd.read_csv(social_network_ads_file)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [16]:
# Features
X = df.iloc[:, [1, 2, 3]].values
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [17]:
# Target
y = df.iloc[:, -1].values
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [20]:
# Feature scaling
# Feature scaling is a method used to normalize the 
# range of independent variables or features of data.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train[:10]

array([[ 1.02532046,  1.92295008,  2.14601566],
       [-0.97530483,  2.02016082,  0.3787193 ],
       [-0.97530483, -1.3822153 , -0.4324987 ],
       [-0.97530483, -1.18779381, -1.01194013],
       [-0.97530483,  1.92295008, -0.92502392],
       [-0.97530483,  0.36757813,  0.29180308],
       [-0.97530483,  0.17315664,  0.14694273],
       [ 1.02532046,  2.02016082,  1.74040666],
       [-0.97530483,  0.75642112, -0.83810771],
       [-0.97530483,  0.27036739, -0.28763835]])

In [21]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

In [22]:
# Prediction values
y_pred = clf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [23]:
# Actual Values
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

In [25]:
print(f"Accuracy: {accuracy*100}%")

Accuracy: 92.5%


In [26]:
print("Confusion Matrix:")
cm

Confusion Matrix:


array([[56,  2],
       [ 4, 18]])