# Numpy Exercises

In [114]:
import numpy as np
print(np.__version__)

1.19.5


## Array Creation

###1. Create a numpy array of size 10, filled with zeros

In [115]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###2. Create a numpy array with values ranging from 10 to 49

In [116]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###3. Create a numpy matrix of 2x2 integers, filled with ones

In [117]:
np.ones((2, 2), dtype=int)

array([[1, 1],
       [1, 1]])

###4. Create a numpy matrix of 3x2 float numbers, filled with ones

In [118]:
np.ones((3, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

###5. Given the x numpy array, create a new numpy array with the same shape and type as x, filled with ones.

In [119]:
x = np.array([0, 0, 0, 0])
np.ones(x.shape, dtype=x.dtype)

array([1, 1, 1, 1])

###6. Given the x numpy matrix, create a new numpy matrix with the same shape and type as x, filled with zeros.

In [120]:
x = np.array([1, 1, 1, 1])
np.zeros(x.shape, dtype=x.dtype)

array([0, 0, 0, 0])

###7. Create a numpy matrix of 4x4 integers, filled with fives

In [121]:
np.full((4, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

###8. Given the x numpy matrix, create a new numpy matrix with the same shape and type as x, filled with sevens.

In [122]:
x = np.full((3, 3), 10)
x

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [123]:
np.full_like(x, 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

###9. Create a 3x3 identity matrix

In [124]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###10. Create a numpy array, filled with 3 random integer values between 1 and 10

In [125]:
np.random.randint(1, 10, size=3)

array([5, 8, 5])

###11. Create a 3x3x3 numpy matrix, filled with random float values

In [126]:
np.random.rand(3, 3, 3)

array([[[0.38009615, 0.51621162, 0.6428323 ],
        [0.03139831, 0.34844764, 0.26218864],
        [0.04753075, 0.65216278, 0.44514696]],

       [[0.49025519, 0.66468321, 0.68628097],
        [0.08305015, 0.71540218, 0.8871526 ],
        [0.2440658 , 0.93557016, 0.13995431]],

       [[0.08767058, 0.12829171, 0.15625116],
        [0.18221546, 0.021256  , 0.39398397],
        [0.22788792, 0.13671966, 0.7089906 ]]])

###12. Given the x python list, convert it to an numpy array

In [127]:
x = [1, 2, 3, 4, 5]
np.array(x)

array([1, 2, 3, 4, 5])

###13. Given the x numpy array, make a copy and store it on y.

In [128]:
x = np.array([1, 1, 1, 1, 1])
y = np.copy(x)
y

array([1, 1, 1, 1, 1])

###14. Create a numpy array with numbers from 1 to 10

In [129]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###15. Create a numpy array with odd numbers between 1 to 10

In [130]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

###16. Create a numpy array with numbers from 1 to 10, in descending order.

In [131]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

###17. Create a 3x3 numpy matrix, filled with values ranging from 0 to 8

In [132]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###18. Show the memory size of the given numpy matrix

In [133]:
matrix = np.arange(10)
matrix.nbytes

80

## Array indexation

###1. Given the numpy array, show it's first element

In [134]:
x = np.array([1, 2, 3, 4])
x[0]

1

###2. Given the numpy array, show it's last element

In [135]:
x[-1]

4

###3. Given the numpy array, show it's first three elements

In [136]:
x[:3]

array([1, 2, 3])

###4. Given the x numpy array, show all middle elements

In [137]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

x[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

###5. Given the numpy array, show the elements in reverse position

In [138]:
x = np.array([1, 2, 3, 4, 5, 6])
x[::-1]

array([6, 5, 4, 3, 2, 1])

###6. Given the x numpy array, show the elements in odd position

In [139]:
x[::2]

array([1, 3, 5])

###7. Given the x numpy matrix, show the last row elements

In [140]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x[-1]

array([7, 8, 9])

###8. Given the numpy matrix, show the first element of first row

In [141]:
x[0, 0]

1

###9. Given the numpy matrix, show the last element of last row

In [142]:
x[-1, -1]

9

###10. Given the numpy matrix, show the middle row elements

In [143]:
x[x.shape[0]//2]

array([4, 5, 6])

###11. Given the x numpy matrix, show the first two elements on the first two rows

In [144]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

x[:2, :2]

array([[1, 2],
       [5, 6]])

###12. Given the x numpy matrix, show the last two elements on the last two rows

In [145]:
x[-2:, -2:]

array([[11, 12],
       [15, 16]])

## Array Manipulation

###1. Convert the given integer numpy array to float

In [146]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 7, 9]])

y = x.astype(np.float)
y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 7., 9.]])

###2. Reverse the given numpy array

In [147]:
x = np.array([1, 2, 3, 4, 5])
x[::-1]

array([5, 4, 3, 2, 1])

###3. Sort the given numpy array

In [148]:
x = np.array([2, 3, 1, 5, 4])
x.sort()
x

array([1, 2, 3, 4, 5])

###4. Given the x numpy array, set the fifth element equal to 1

In [149]:
x = np.array([2, 3, 1, 5, 4])
x[4] = 1
x

array([2, 3, 1, 5, 1])

###5. Given the x numpy array, change the 50 with a 40

In [150]:
x = np.array([2, 3, 1, 50, 4])
x[np.where(x==50)] = 40
x

array([ 2,  3,  1, 40,  4])

###6. Given the x numpy matrix, change the last item on the last row with a 0

In [151]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
x[-1, -1] = 0
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

###7. Given the x numpy matrix, add 5 to every element

In [152]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
x+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Boolean Arrays

###1. given the x numpy array, make a mask showing negative elements

In [153]:
x = np.array([[-1, 2, 3],
              [-4, -5, 6],
              [7, 8, -9]])

x < 0

array([[ True, False, False],
       [ True,  True, False],
       [False, False,  True]])

###2. Get the negative elements

In [154]:
x[x < 0]

array([-1, -4, -5, -9])

###3. Get numbers higher than 5

In [155]:
x[x > 5]

array([6, 7, 8])

###4. Get numbers higher than the elements mean

In [156]:
x[x > x.mean()]

array([2, 3, 6, 7, 8])

## Logic Functions

###1. Given the x numpy array, return True if none of its elements is zero

In [157]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x.all()

True

###2. Return true if any of the elements are zero

In [158]:
~x.all()

False

## Summary Statistics

###1. Given the x numpy array, show the sum of its elements

In [159]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x.sum()

45

###2. Show the mean

In [160]:
x.mean()

5.0

###3. Show the sum of its columns

In [161]:
x.sum(axis=0)

array([12, 15, 18])

###4. Show the max value

In [162]:
x.max()

9