In [1]:
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('float64')

In [9]:
a[0], a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3])

In [11]:
a[1:3]

array([2, 3])

In [12]:
a[1:-1]

array([2])

In [13]:
a[::2]

array([1, 3])

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Dimensions And Shapes

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.shape

(2, 3)

In [17]:
a.ndim

2

In [18]:
a.size

6

## Indexing and slicing of matrices

In [19]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a[1]

array([4, 5, 6])

In [21]:
a[1][0]

4

In [22]:
a[1, 0]

4

In [23]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
a[:2, :2]

array([[1, 2],
       [4, 5]])

In [26]:
a[1] = np.array([10, 20, 30])
a

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 7,  8,  9]])

## Summary Statistics

In [27]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [28]:
a.sum()

10

In [29]:
a.mean()

2.5

In [30]:
a.std()

1.118033988749895

In [31]:
a.var()

1.25

In [32]:
a = np.array([[1, 2, 3],
              [11, 12, 13],
              [21, 22, 23]])
a

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [33]:
a.sum(axis=1) # Row

array([ 6, 36, 66])

In [34]:
a.sum(axis=0) # Col

array([33, 36, 39])

In [35]:
a.mean(axis=1)

array([ 2., 12., 22.])

In [36]:
a.mean(axis=0)

array([11., 12., 13.])

## Broadcasting and Vectorized operations

In [37]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [38]:
a+10

array([10, 11, 12, 13])

In [39]:
a*10

array([ 0, 10, 20, 30])

In [40]:
a += 100
a

array([100, 101, 102, 103])

In [41]:
l = np.array([1, 2, 3])
[i*10 for i in l]

[10, 20, 30]

In [42]:
a = np.arange(4)
b = np.array([10, 20, 30, 40])
a, b

(array([0, 1, 2, 3]), array([10, 20, 30, 40]))

In [43]:
a+b, a*b

(array([10, 21, 32, 43]), array([  0,  20,  60, 120]))

## Boolean Arrays

In [44]:
a = np.arange(4)

In [45]:
a > 2

array([False, False, False,  True])

In [46]:
a[a > 2]

array([3])

In [47]:
a.mean()

1.5

In [48]:
a[a > a.mean()]

array([2, 3])

In [49]:
a[~(a > a.mean())]

array([0, 1])

In [50]:
a == 0

array([ True, False, False, False])

In [51]:
a == 1

array([False,  True, False, False])

In [52]:
(a == 0) | (a == 1)

array([ True,  True, False, False])

In [53]:
(a <= 2) & (a % 2 == 0)

array([ True, False,  True, False])

## Linear Algebra

In [54]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
b = np.array([[6, 5],
              [4, 3],
              [2, 1]])
b

array([[6, 5],
       [4, 3],
       [2, 1]])

In [56]:
a.dot(b) # Dot Product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [57]:
a @ b # Dot product operator

array([[20, 14],
       [56, 41],
       [92, 68]])

In [58]:
b.T # Transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [59]:
b.T @ a

array([[36, 48, 60],
       [24, 33, 42]])

## Size and Objects in Memory

In [60]:
import sys

sys.getsizeof(1)

28

In [61]:
sys.getsizeof(10**100)

72

In [62]:
np.dtype(int).itemsize

4

In [63]:
np.dtype(float).itemsize

8

In [64]:
sys.getsizeof([1])

64

In [65]:
np.array([1]).nbytes

4

## Performance

In [66]:
arr = list(range(1000000))
%time sum([x**2 for x in arr])

Wall time: 216 ms


333332833333500000

In [67]:
arr = np.arange(1000000)
%time np.sum(arr**2)

Wall time: 2.01 ms


584144992

## Useful Numpy Functions

In [68]:
np.random.random(size=2)

array([0.13151456, 0.87426942])

In [69]:
np.random.normal(size=2)

array([-0.54436824,  0.13025301])

In [70]:
np.random.rand(2, 4)

array([[0.40595688, 0.0094404 , 0.91587432, 0.89255036],
       [0.13258244, 0.23202466, 0.35510477, 0.72519923]])

In [71]:
np.arange(10).reshape(2, 5) # Reshape 1x10 -> 2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
np.linspace (0, 1, num=5) # Evenly seperated values in range(0, 1)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [73]:
np.linspace (0, 1, num=20, endpoint=False) # Endpoint is not included

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [74]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [75]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye (3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.eye (8, 4, k=-3) 
# k is the index of the diagonal, 
# +ve val refers of upper diag, 
# and -ve refers to lower diag 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])