In [1]:
import numpy as np

In [2]:
# Defining network
input_layer_neurons = 2
hidden_layer_neurons = 3
output_layer_neurons = 1

print(f"Input layer neurons: {input_layer_neurons}")
print(f"Hidden layer neurons: {hidden_layer_neurons}")
print(f"Output layer neuron: {output_layer_neurons}")

Input layer neurons: 2
Hidden layer neurons: 3
Output layer neuron: 1


In [3]:
wh = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
bh = np.random.uniform(size=(1, hidden_layer_neurons))
wout = np.random.uniform(size=(hidden_layer_neurons, output_layer_neurons))
bout = np.random.uniform(size=(1, output_layer_neurons))

print(f"Weights from input layer to hidden layers: \n{wh}\n")
print(f"Bias in between input layer and hidden layers: \n{bh}\n")
print(f"Weights in between hidden layer and output layers: \n{wout}\n")
print(f"Bias in between hidden layer and output layers: \n{bout}\n")

Weights from input layer to hidden layers: 
[[0.07665443 0.79617163 0.80714183]
 [0.32219442 0.97081914 0.8373135 ]]

Bias in between input layer and hidden layers: 
[[0.00789093 0.36282925 0.24478328]]

Weights in between hidden layer and output layers: 
[[0.0767625 ]
 [0.04666676]
 [0.89543769]]

Bias in between hidden layer and output layers: 
[[0.8736009]]



In [4]:
# Initializaion
epoch = 7000 # Training iterations
learning_rate = 0.1

# Inputs
X = np.array([[2, 9], [1, 5], [3, 6]], dtype=float)

# Outputs
y = np.array([[1], [0], [1]], dtype=float)

# Normalizing inputs
X = X/np.amax(X, axis=0)
X

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [5]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x*(1-x)

In [6]:
# Forward propgation
for i in range(epoch):
    h_activation = sigmoid(np.dot(X, wh) + bh)
    output = sigmoid(np.dot(h_activation, wout) + bout)

    # Backpropogation
    e_out = y-output # Error at output layer
    output_gradient = derivatives_sigmoid(output) # Error portion at output layer
    d_output = e_out*output_gradient

    e_hidden = d_output.dot(wout.T)
    hidden_gradient = derivatives_sigmoid(h_activation)
    d_hidden = e_hidden*hidden_gradient

    wout += h_activation.T.dot(d_output) * learning_rate # Each hidden layer output value * final output layer
    wh += X.T.dot(d_hidden) * learning_rate # change weights between input layer and hidden layer

print(f"Input: \n {X}\n")
print(f"Actual Output: \n{y}\n")
print(f"Predicted Output: \n{output}")

Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[1.]
 [0.]
 [1.]]

Predicted Output: 
[[0.76031744]
 [0.26033622]
 [0.95134958]]
